apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ template "percona.fullname" . }}
  labels:
    app: {{ template "percona.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "percona.fullname" . }}
  serviceName: {{ template "percona.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "percona.fullname" . }}
    spec:
      initContainers:
      - name: "remove-lost-found"
        image: "busybox:1.25.0"
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        command:
        - "rm"
        - "-fr"
        - "/var/lib/mysql/lost+found"
#        volumeMounts:
#        - name: data
#          mountPath: /var/lib/mysql
      containers:
      - name: {{ template "percona.fullname" . }}
        image: "{{ .Values.imageRepo }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        env:
        {{- if .Values.mysqlAllowEmptyPassword }}
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "true"
        {{- else }}
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "percona.fullname" . }}
              key: mysql-root-password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "percona.fullname" . }}
              key: mysql-password
        {{- end }}
#        - name: MYSQL_USER
#          value: {{ default "" .Values.mysqlUser | quote }}
#        - name: MYSQL_DATABASE
#          value: {{ default "" .Values.mysqlDatabase | quote }}
        - name: CLUSTER_NAME
          value: {{ template "percona.fullname" . }}
        - name: K8S_SERVICE_NAME
          value: {{ template "percona.fullname" . }}-xtradb-cluster
        - name: LOG_TO_STDOUT
          value: "true"
        - name: DISCOVERY_SERVICE
          value: kubernetes
        - name: DEBUG
          value: "true"
        ports:
        - name: mysql
          containerPort: 3306
        - name: galera
          containerPort: 4567
        - name: state-transfer
          containerPort: 4568
        - name: state-snapshot
          containerPort: 4444
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: ["mysql", "-h", "127.0.0.1", "-e", "SELECT 1"]
          initialDelaySeconds: 5
          timeoutSeconds: 1
#        volumeMounts:
#        - name: data
#          mountPath: /var/lib/mysql
#      volumes:
#      - name: data
#      {{- if .Values.persistence.enabled }}
#        persistentVolumeClaim:
#          claimName: {{ template "percona.fullname" . }}
#      {{- else }}
#        emptyDir: {}
#      {{- end -}}
