apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  labels:
    app: percona-galera
  name: percona-galera
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ template "percona.fullname" . }}
  serviceName: {{ template "percona.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "percona.fullname" . }}
    spec:
      containers:
      - name: {{ template "percona.fullname" . }}
        image: paulczar/percona-xtradb-cluster:5.7.19
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: not-a-secure-password
        - name: CLUSTER_NAME
          value: {{ template "percona.fullname" . }}
        - name: K8S_SERVICE_NAME
          value: {{ template "percona.fullname" . }}-xtradb-cluster
        - name: LOG_TO_STDOUT
          value: "true"
        - name: DISCOVERY_SERVICE
          value: kubernetes
        - name: DEBUG
          value: "true"
        livenessProbe:
          exec:
            command: ["mysqladmin", "-p$(MYSQL_ROOT_PASSWORD)", "ping"]
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: ["mysql", "-h", "127.0.0.1", "-p$(MYSQL_ROOT_PASSWORD)", "-e", "SELECT 1"]
          initialDelaySeconds: 60
          periodSeconds: 2
          timeoutSeconds: 1
